### ISSUE TITLE
Make webpage test URL configurable

### ISSUE THREAD

**Issue by redonkulus** [perflint/perflint#2]
At my company, we have an internal instance of webpacktest to test internal URLs. Would be nice to make this configurable in the tool:

https://github.com/perflint/perflint/blob/master/lib/service/webpagetest.js#L114

**Comment by matthojo** [comment]
Great idea. I'll see if I can get this into the next release, shouldn't be too difficult.

**Comment by matthojo** [comment]
Started work on this with https://github.com/perflint/perflint/commit/578bd1dac994952b54a0ac0ea660d49dc0290e40.

Remaining work;
- [x] Tests still need adding
- [ ] Validate it works with real custom WPT servers
- [x] Allow server to be set with environment variable - https://github.com/perflint/perflint/commit/eaa5ade7f3bce5bc74e11dd7e376e1e420b4d17c

**Comment by matthojo** [comment]
This is now available on `v0.0.3`.
Documentation: https://perflint.readme.io/v0.0.3/docs/command-line-interface#-s-server-string

I'll close once tests and there is validation of it working with hosted WPT servers.
